### ISSUE TITLE
Add support for bz2 archives

### ISSUE THREAD

**Issue by benjamin-texier** [upciti/ops2deb#129]
It would be interesting if ops2deb could decompress bz2 archives.

Example [restic](https://github.com/restic/restic/releases/tag/v0.12.1):

```yaml
- name: restic
   version: 0.12.1
   homepage: https://restic.net/
   summary: fast, secure, efficient backup program
   description: restic is a backup program that is fast, efficient and secure.
   fetch:
     url: https://github.com/restic/restic/releases/download/v{{version}}/restic_{{version}}_linux_{{goarch}}.bz2
     sha256:
       amd64: 11d6ee35ec73058dae73d31d9cd17fe79661090abeb034ec6e13e3c69a4e7088
       armhf: f27c3b271ad36896e22e411dea4c1c14d5ec75a232538c62099771ab7472765a
       arm64: c7e58365d0b888a60df772e7857ce8a0b53912bbd287582e865e3c5e17db723f
   script:
     - mv restic_{{version}}_linux_{{goarch}} {{src}}/usr/bin/restic
```

See:
* [wakemeops#250](https://github.com/upciti/wakemeops/pull/250/files)
* [python - bz2](https://docs.python.org/3/library/bz2.html)
